require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'test/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'config.ru'
    - 'Gemfile'
    - 'Rakefile'
Style/FrozenStringLiteralComment:
    Enabled: false
